require 'user.launch'
require 'user.core.options'
require 'user.core.keymaps'
require 'user.core.autocmds'
require 'user.themes'
spec 'user.autotab'
spec 'user.comment'
spec 'user.gitsigns'
spec 'user.whichkey'
spec 'user.telescope'
spec 'user.arrow'
-- spec 'user.harpoon'
spec 'user.cmp'
spec 'user.lsp'
spec 'user.format'
spec 'user.todo'
spec 'user.mini'
spec 'user.treesitter'
spec 'user.neo-tree'
spec 'user.terminal'
spec 'user.autopairs'
spec 'user.hop'
spec 'user.breadcrumbs'
spec 'user.navic'
spec 'user.tmux'
spec 'user.maximize'
-- Extra
spec 'user.extras.zen-mode'
spec 'user.extras.ufo'
-- spec 'user.extras.xcodebuild'
require 'user.lazy'
require 'current-theme'

-- The line beneath this is called `modeline`. See `:help modeline`
-- vim: ts=2 sts=2 sw=2 et
